Repository maticnetwork/zkevm-docs, pull requests merged in 2023-07, with the labels that each got.

#49 Fixes issue #48
  docs/zkProver/paddingkk-sm.md
Labels: fix, protocol, need: review

#51 add: polygon zkevm faucet document
  docs/zkevm-faucet.md
  sidebars.js
  static/img/zkevm/confirm-zketh.png
  static/img/zkevm/faucet-zketh.png
  static/img/zkevm/success-zketh.png
Labels: add, developers, need: review

#52 update: transaction execution document
  docs/protocol/transaction-execution.md
Labels: update, protocol, need: review

#53 fix: broken link on gas station document
  docs/zkevm-gas-station.md
Labels: fix

#54 add: guides for deploying smart contracts to zkEVM
  docs/develop.md
  docs/guides/figures/contract-foundin-polygonscan.png
  docs/guides/figures/end-product-nft-code.png
  docs/guides/figures/flatten-code-remix.png
  docs/guides/figures/forge-no-git-fix.png
  docs/guides/figures/goerlifaucet-dot-com.png
  docs/guides/figures/mintto-fields-fillin.png
  docs/guides/figures/proj-created-outcome.png
  docs/guides/figures/sc-deploy-success.png
  docs/guides/figures/sc-deploy-success2.png
  docs/guides/figures/success-deploy-sbtdotsol.png
  docs/guides/figures/success-forge-build.png
  docs/guides/figures/test-forge-build.png
  docs/guides/figures/upgrade-overview.png
  docs/guides/using-foundry.md
  docs/guides/using-hardhat.md
  docs/guides/zkevm-beginner.md
  docs/guides/zkevm-faucet.md
  docs/introduction.md
  sidebars.js
Labels: add, developers, need: review

#56 add: guides for writing and verifying contracts
  docs/develop.md
  docs/guides/autocode-smart-contract.md
  docs/guides/figures/end-product-nft-code.png
  docs/guides/using-foundry.md
  docs/guides/using-hardhat.md
  docs/guides/verify-smart-contract.md
  docs/guides/zkevm-beginner.md
  sidebars.js
Labels: add, developers, need: review

#58 add: css styling for new docs
  sidebars.js
  src/css/custom.css
Labels: update, ui/ux

#59 add: full zkEVM deployment guide
  docs/setup-zkevm.md
  sidebars.js
Labels: add, developers, need: review

#60 update: sidebar changes for zkEVM setup guides
  docs/setup-local-node.md
  docs/setup-production-node.md
  docs/setup-zkevm.md
  sidebars.js
  src/pages/index.js
Labels: update, developers, need: review

#66 update: gas station document
  docs/zkevm-gas-station.md
Labels: update, developers

#67 update: bump dependencies
  docs/guides/using-foundry.md
  yarn.lock
Labels: update, action
