Repository maticnetwork/zkevm-docs, pull requests merged in 2023-05, with the labels that each got.

#10 fix: appearance of code text with links
  docs/bridge-to-zkevm.md
  docs/develop.md
  docs/introduction.md
  docusaurus.config.js
  src/css/custom.css
  src/pages/index.js
Labels: fix, ui/ux

#11 action: add Google Analytics to docs
  docusaurus.config.js
Labels: action

#12 action: update algolia docsearch
  docusaurus.config.js
Labels: action

#18 add: Proving Architecture document and images
  docs/zkProver/figures/10prf-rec-proving-arch-outline.png
  docs/zkProver/figures/11prf-rec-build-zkevm-stark.png
  docs/zkProver/figures/12prf-rec-convert-verification-to-circuit.png
  docs/zkProver/figures/13prf-rec-convert-zkevm-verifier-to-stark.png
  docs/zkProver/figures/14prf-rec-convert-stark-to-circuit-verifier.png
  docs/zkProver/figures/15prf-rec-convert-circuit-to-assoc-stark.png
  docs/zkProver/figures/16prf-rec-recursive2-circuit.png
  docs/zkProver/figures/17prf-rec-stark-to-circuit-recursive2.png
  docs/zkProver/figures/18prf-rec-recursive2-circuit-2-stark.png
  docs/zkProver/figures/19prf-rec-recursive2-stark-to-recursivef-circuit.png
  docs/zkProver/figures/20prf-rec-recursivef-circuit-2-stark.png
  docs/zkProver/figures/21prf-rec-recursivef-stark-to-final-circom.png
  docs/zkProver/proving-architecture.md
  sidebars.js
Labels: add, protocol

#24 update: CIRCOM doc and broken links
  docs/PIL/pil-arguments.md
  docs/zkProver/circom-intro-brief.md
  docusaurus.config.js
Labels: update

#21 update: change newsletter link
  src/pages/index.js
Labels: update, action

#20 update: keywords for documentation SEO
  docs/PIL/connect-arg.md
  docs/PIL/connect-programs.md
  docs/PIL/cyclic-nature.md
  docs/PIL/filling-polynomial.md
  docs/PIL/generate-proof.md
  docs/PIL/introduction.md
  docs/PIL/permutation-arg.md
  docs/PIL/pil-arguments.md
  docs/PIL/pil-compile.md
  docs/PIL/pil-config.md
  docs/PIL/pil-plonk.md
  docs/PIL/public-values.md
  docs/PIL/simple-program.md
  docs/architecture.md
  docs/bridge-to-zkevm.md
  docs/develop.md
  docs/faq/zkevm-eth-faq.md
  docs/faq/zkevm-general-faq.md
  docs/faq/zkevm-protocol-faq.md
  docs/glossary.md
  docs/introduction.md
  docs/open-source-repos.md
  docs/protocol/admin-role.md
  docs/protocol/aggregator-resistance.md
  docs/protocol/bridge-smart-contract.md
  docs/protocol/emergency-state.md
  docs/protocol/evm-differences.md
  docs/protocol/exit-tree.md
  docs/protocol/flow-of-assets.md
  docs/protocol/incentive-mechanism.md
  docs/protocol/introduction.md
  docs/protocol/l2-transaction-cycle-intro.md
  docs/protocol/sequencer-resistance.md
  docs/protocol/state-management.md
  docs/protocol/transaction-aggregation.md
  docs/protocol/transaction-batching.md
  docs/protocol/transaction-execution.md
  docs/protocol/transaction-sequencing.md
  docs/protocol/upgradability.md
  docs/protocol/zkevm-bridge.md
  docs/risk-disclosure.md
  docs/setup-local-node.md
  docs/setup-production-node.md
  docs/zkASM/basic-syntax.md
  docs/zkASM/introduction.md
  docs/zkASM/some-examples.md
  docs/zkevm-gas-station.md
  docs/zknode/overview.md
Labels: update, developers, protocol, faq

#15 add: SECURITY.md
  SECURITY.md
Labels: action, add

#29 add: MaticJS client API documentation
  docs/maticjs/common-methods.md
  docs/maticjs/initialize-zkevm.md
  docs/maticjs/install-sdk.md
  docs/maticjs/zkevm-client-erc20.md
  sidebars.js
  src/css/custom.css
Labels: add, developers
